### ISSUE TITLE
Link in BAP page looks to be missing for Where?

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#10]
Change BAP on the Navigation bar to Bandwidth Aggregation Program (BAP)

- [x] Remove sections ISP Analysis, ISP Contract Negotiations and Managed ISP Management as it is already in the section What we do for NGOs, 
- [x] Check the link for Where as the image is not showing up.
![cap 13](https://cloud.githubusercontent.com/assets/20802030/17346024/c076f444-58bd-11e6-970b-5d20f09d37b2.PNG)

- [x] Remove How? in the wording section as the image can show How?
![cap 15](https://cloud.githubusercontent.com/assets/20802030/17347058/bbcfd9ba-58c2-11e6-9991-25d01256bd8b.PNG)

- [x] Increase the font size under each image as it is small and hard to read
![cap 16](https://cloud.githubusercontent.com/assets/20802030/17347088/edb35498-58c2-11e6-8a33-e00ebf45c9d7.PNG)

**Comment by ariperez** [comment]
@dataguy23us when it comes to the Navbar, I feel like we are pushing the limits of how many things fit across the width. I can expand BAP, but can you just comment back with a list of every Link you want in the correct order. Here is what I got so far:

- What we do for NGOs
- BAP
- Meraki
- Coverage Map
- About Us
- REQUEST PRICING


![image](https://cloud.githubusercontent.com/assets/2553469/17373238/4b0bc6cc-5975-11e6-84a5-029b52c85270.png)

**Comment by dataguy23us** [comment]
ABOUT
WHAT WE DO
BANDWIDTH AGGREGATION PROGRAM (BAP)  (This is trademarked so it needs to be spelled out)
COVERAGE MAP
MERAKI
REQUEST PRICING

Please add Trouble Tickets in the footer section

**Comment by dataguy23us** [comment]
Ari,

Could we consider a two level Navigation Bar? This might also increase the size of the logo.

The top bar might have About, Meraki, Trouble Tickets, Contact Us

Main Navigation Bar
WHAT WE DO
BANDWIDTH AGGREGATION PROGRAM (BAP) 
COVERAGE MAP
REQUEST PRICING

This is what CRS.org did
![cap 17](https://cloud.githubusercontent.com/assets/20802030/17375297/34f777ec-5965-11e6-9e32-29f045da90ff.PNG)

**Comment by ariperez** [comment]
ok. I'll give the two level Navbar a shot. It's not supported by default in Materialize CSS so we will see the level of effort it takes.

**Comment by ariperez** [comment]
also splitting off the Navbar topic into a separate issue. #11

**Comment by ariperez** [comment]
@dataguy23us ; let me know if the above comments are complete. (minus the navbar since we split that off) Go ahead and hit "Close and Comment" if so.

https://github.com/telecom4good/telecom4good.github.io/issues/10
