### ISSUE TITLE
Navbar Updates

### ISSUE THREAD

**Issue by ariperez** [telecom4good/telecom4good.github.io#11]
ABOUT
WHAT WE DO
BANDWIDTH AGGREGATION PROGRAM (BAP)  (This is trademarked so it needs to be spelled out)
COVERAGE MAP
MERAKI
REQUEST PRICING

Please add Trouble Tickets in the footer section

----

Could we consider a two level Navigation Bar? This might also increase the size of the logo.

The top bar might have About, Meraki, Trouble Tickets, Contact Us

Main Navigation Bar
WHAT WE DO
BANDWIDTH AGGREGATION PROGRAM (BAP) 
COVERAGE MAP
REQUEST PRICING

This is what CRS.org did
![cap 17](https://cloud.githubusercontent.com/assets/20802030/17375297/34f777ec-5965-11e6-9e32-29f045da90ff.PNG)

**Comment by dataguy23us** [comment]
Thank you
