### ISSUE TITLE
Please add image of Dago Lin to staff section

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#14]
Please add Dago Lin's image to staff section
![dago lin](https://cloud.githubusercontent.com/assets/20802030/17410908/a3bd2dc8-5a2a-11e6-974e-ca6accab8ada.jpg)

**Comment by ariperez** [comment]
@dataguy23us : completed

**Comment by dataguy23us** [comment]
Thank you
