### ISSUE TITLE
Convert to Jekyll Website

### ISSUE THREAD

**Issue by ariperez** [telecom4good/telecom4good.github.io#15]
Currently the website is completely static which requires me to duplicate Navbar and Footer information across every web page individually.  This work has become time consuming and risks introducing bugs.

By shifting to Jekyll, I can create the code for the footer and Navbar once, and share across all the pages.

**Comment by dataguy23us** [comment]
I assumed that you created a master header footer and it duplicated on all pages. That way if you made one change it followed on all pages. How long does it take to shift to Jekyll? is this something that is quick and easy?

**Comment by ariperez** [comment]
complete

**Comment by dataguy23us** [comment]
Thank you
