### ISSUE TITLE
Add New Slider Images

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#23]
1.	Add new slider image from OneDrive and add in the text in this image below.
I also like the text box that highlights the text more clearly. Link the Learn More to the BAP page

![cap27](https://cloud.githubusercontent.com/assets/20802030/17529099/e11505ce-5e26-11e6-9162-14bc4d9067ef.png)

2.    Add new slider image and use similar font with the text below

![cap28](https://cloud.githubusercontent.com/assets/20802030/17529136/fb5a83f0-5e26-11e6-9ba6-c62afae61ecc.png)

3.    Add New Slider Banner. The image in on the OneDrive account
a. I like the black frame around the wording to make it bold and stand out. Remove the red heart and just leave Learn More
The wording should read:
30-DAY Free Internet Trials
We are offering a special 30-Day Free Internet Service Trials within 21 Countries in Africa.

![cap40](https://cloud.githubusercontent.com/assets/20802030/17529179/3683240a-5e27-11e6-934d-53acd81e6fe9.png)

**Comment by ariperez** [comment]
@dataguy23us ; Can you review for just image sizes? Not the text?

**Comment by ariperez** [comment]
check for order as well.  May take a second to upload.

**Comment by dataguy23us** [comment]
I see the images. There are only 4. You lost the one of the girl. Can we have more than 4?

Also can you make the images smaller in Photoshop so that we can see more of the image versus a thin portion shown currently?  Also the image of the data going through the tunnel is the wrong one. There is a different one in OneDrive that is blue. Please see above in this issue.

If you need me to change the size of the image I can do that just let me know.

**Comment by dataguy23us** [comment]
can you make the images in the slider taller so that we can see more of the image? The images are impactful and I want to make sure we get the most out of each slider image

**Comment by ariperez** [comment]
@dataguy23us ; ok, so I increased the height, and added the girl, and switched incorrect pipe image.

Lets see if the height is ok before I start resizing in photoshop. (Or I can give you the dimensions to make sure your ok with any stretching as it most likely occur)

**Comment by dataguy23us** [comment]
can we make it a even taller? Also I can reshape in Photoshop pretty quickly.

**Comment by ariperez** [comment]
you're about to get your developer badge. :)

https://github.com/telecom4good/telecom4good.github.io/blob/master/js/init.js

go ahead and edit the height to your hearts content.

**Comment by ariperez** [comment]
it changes in pixels.

**Comment by dataguy23us** [comment]
Thank you for that. I checked 750, 800 and it makes it too tall. Let's change the image size to see if it shows more in the 700 height.

What is the width dimension in pixel would you like and I can send a test image to you

**Comment by dataguy23us** [comment]
Ari,

Please try these images. 
![lion-800](https://cloud.githubusercontent.com/assets/20802030/17567351/cc47550c-5ef3-11e6-9fd9-2d599e079ff7.png)
![data-800](https://cloud.githubusercontent.com/assets/20802030/17567350/cc42aab6-5ef3-11e6-9150-a1be862cec83.png)
![hands-800](https://cloud.githubusercontent.com/assets/20802030/17567352/cc4ae2ee-5ef3-11e6-993d-d4f7a03c10df.png)
![watch-800](https://cloud.githubusercontent.com/assets/20802030/17567369/e224a974-5ef3-11e6-9806-baaf532cf7e2.png)
![woman-800](https://cloud.githubusercontent.com/assets/20802030/17567370/e22f47ee-5ef3-11e6-8a57-7c736906dae9.png)

**Comment by dataguy23us** [comment]
Ari and Ryan,

I am still unable to add the new images to the website. Can you assist please?

**Comment by ariperez** [comment]
images updated.

**Comment by ariperez** [comment]
may take a few minutes to upload

**Comment by dataguy23us** [comment]
Thank you
