### ISSUE TITLE
Changes to hand shake image towards bottom of home page

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#26]
1. Make the brown oval less wide so that the text can be responsive
2. Center the text
3. Change the text to 2 lines that reads"
Collaboration with other NGOs through the 
Bandwidth Aggregation Program (BAP)
4.  Link the LEARN MORE button to the BAP page

![cap36](https://cloud.githubusercontent.com/assets/20802030/17531962/1b6590f2-5e33-11e6-82c0-16cfd1980aaf.png)

**Comment by ariperez** [comment]
Let me know if this is better.

**Comment by dataguy23us** [comment]
Ari,

Can you make the text break to a second line of text after "the" the second line of text would be Bandwidth Aggregation Program (BAP)

**Comment by dataguy23us** [comment]
Ari,

I added a <br> to separate the lines but I could not figure out how to center the text in the middle of the Brown Oval. I tried to add <center> and </center> after but it didn't.

Can you correct for me please? This is what is looks like now.

![cap42](https://cloud.githubusercontent.com/assets/20802030/17539230/590d59de-5e61-11e6-9969-cb5cad579615.PNG)

**Comment by ariperez** [comment]
Good instinct with the `<br>`.  Typically this works but because of the type of centering I had to use some padding.  Let me know if its better.

**Comment by dataguy23us** [comment]
Thanks Ari, It is better.
