### ISSUE TITLE
Remove the First, pick a template at the bottom of the page

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#27]
1. Remove the First, pick a template at the bottom of the page
![cap37](https://cloud.githubusercontent.com/assets/20802030/17531989/4d9269d8-5e33-11e6-99fb-31defbfe894d.png)

**Comment by ariperez** [comment]
This is really strange!  I can't find those words across any of the code.  Can you try in a different browser?  

If its still there, 'save as' the web page and send me the html code.

**Comment by dataguy23us** [comment]
It is gone now. Thank you
