### ISSUE TITLE
Can you show me how and where to upload images 

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#28]
Ari,

Can you show me where to upload images and I can play with sizing. I think I can just replace the image
<img src="./images/women.jpg"> to the new name of the image to change as long as it is in the image folder.

To upload images, do I go to the image folder and upload each image? is it that easy?

**Comment by ariperez** [comment]
so this one is a bit trickier...

1. Navigate to the images folder:
https://github.com/telecom4good/telecom4good.github.io/tree/master/images

2. On the top right you'll see a button for "Upload Files"
![image](https://cloud.githubusercontent.com/assets/2553469/17592386/1c5983f0-5fb0-11e6-943b-0ff002af2cc9.png)

3. Ensure the file name is the exact same one as the one you are replacing.  

(As long those three things take place, it should update immediately)

@ryandorr17


Github Article
https://help.github.com/articles/adding-a-file-to-a-repository/

**Comment by dataguy23us** [comment]
Thanks Ari The image that i was trying to replace was lion.jpg with lion-800.png. I uploaded the image and I can find it in the image section but it is a different name. Should I rename the file lion-800.png lion.jpg through Photoshop and re-upload?

**Comment by ariperez** [comment]
Yes.  If the name is not exactly the same, it won't overwrite. Done correctly you should see the timer on the right side reset to your upload time. 

![image](https://cloud.githubusercontent.com/assets/2553469/17592878/0b61e48c-5fb2-11e6-8814-7a5ae9c2b7b3.png)

**Comment by dataguy23us** [comment]
OK I will check shortly. Thank you
