### ISSUE TITLE
Update Banner in Carousel

### ISSUE THREAD

**Issue by ariperez** [telecom4good/telecom4good.github.io#3]
![collaboration-banner 2 slim](https://cloud.githubusercontent.com/assets/2553469/17341880/afe2b8fa-58c4-11e6-92e2-00fe9ff024bf.png)

**Comment by ariperez** [comment]
Can we take the text off the image and we will use HTML so it's SEO ready.

**Comment by dataguy23us** [comment]
Yes I will resend the image without text shortly

Robert Anderson
President
Telecom4Good.Org<http://telecom4good.org/>
+1-949-274-3877<tel:+1-949-274-3877> Direct
+1-949-274-3877<tel:+1-949-274-3877> Whastapp
Skype: dataguy23us

[cid:image001.png@01D0FA43.AAE372D0]

On Aug 2, 2016, at 12:49 PM, Ari Perez <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we take the text off the image and we will use HTML so it's SEO ready? @dataguy23us<https://github.com/dataguy23us>

-

**Comment by dataguy23us** [comment]
Here is the image without the wording embedded

![collaboration-banner 3](https://cloud.githubusercontent.com/assets/20802030/17343820/729f1822-58b4-11e6-8a58-6f52bf2604eb.png)
