### ISSUE TITLE
Add LEARN MORE buttons to each of the slider images in Yellow with Black UPPER CASE text.

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#36]
1. Add LEARN MORE buttons to each of the Slider Images like this one that is used on the maps here
![cap48](https://cloud.githubusercontent.com/assets/20802030/17718848/410e9644-63cb-11e6-8ea9-c1d4e3eede37.PNG)

**Comment by ariperez** [comment]
These are added, need to know where they link to.

**Comment by dataguy23us** [comment]
Thank you Ari for your question. Please link each slider image to these pages.
Slider Image Woman /what_we_do_for_ngos.html
Slider Image Hands /bap.html
Slider Image Data Funnel /bap.html
Slider Image Lion /what_we_do_for_ngos.html
Slider Image Watch /30-day.html

Thank you

**Comment by dataguy23us** [comment]
I changed the code on the /index.html to reflect the link to for each of the LEARN MORE in the slider images and everything works. BUT if I click on the Logo to take me back to the home page it goes back to the previous LEARN MORE links to /participate.html. Can we change the logo to go to the main home page with the correct links for the LEARN MORE or is there a header or nav bar that we need to relink the logo to?

**Comment by ariperez** [comment]
try refreshing and trying again, not getting that behavior on my end

thanks for updating!

**Comment by dataguy23us** [comment]
Works. Thank you
