### ISSUE TITLE
Create 30-Day Free Internet Trial in Africa page /30-day.html

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#40]
The slider image that has the 30-Day Free Internet Trials in Africa will need a page to link to from the LEARN MORE button

Create a new referring page /30-day.html

include the following embedded code to the Smartsheet web form
<iframe width="1000" height="700" frameborder="0" src="https://app.smartsheet.com/b/form?EQBCT=39a014142ef54c078f03a896c9334e7e"></iframe>

**Comment by ryandorr17** [comment]
You may want to remove the blue background and t4g icon from this form

**Comment by dataguy23us** [comment]
I have updated the webform to remove the blue background.

Thank you
