### ISSUE TITLE
Reduce Map size to fit in box and other changes on /participate  page

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#42]
Ryan,

Great job on building the participate page.

Here are some additional changes to make it perfect. 

![cap53](https://cloud.githubusercontent.com/assets/20802030/17756892/e943ed92-6497-11e6-977d-0df383626b5d.PNG)

**Comment by dataguy23us** [comment]
Asia and Middle East need to be listed separately since there are different BAP web forms for each  linked separate pages.

me-bap.html should be linked to Middle East Countries (same map as Asia but shown separately)
asia-bap.html should be linked to Asia Countries (same map as Middle East but shown separately)

**Comment by ariperez** [comment]
complete

**Comment by dataguy23us** [comment]
Thank you
