### ISSUE TITLE
Add Pulldown Menu to WHAT WE DO

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#51]
![cap62](https://cloud.githubusercontent.com/assets/20802030/17982653/b351979e-6abd-11e6-832a-7f993dd9f37a.PNG)

**Comment by ariperez** [comment]
@ryandorr17 - need some assistance with these anchor tags

**Comment by dataguy23us** [comment]
Link the following menu items to the following pages and sections within the page

- Bandwidth Aggregation Program (BAP) to /bap.html
- Internet RFP Strategy to /rfp.html
- Pre-negotiated Internet Pricing to the section on the /what_we_do_for_ngos.html
- ISP Analysis to section on the /what_we_do_for_ngos.html
- ISP Contract Negotiation to section on the /what_we_do_for_ngos.html
- Managed ISP Implementation to section on the /what_we_do_for_ngos.html

**Comment by ariperez** [comment]
I updated the links as stated above, but the jump to "section" (ie Managed ISP...) is what I referenced in the anchor tag comment. We can close this or wait for Ryan's help here.

**Comment by dataguy23us** [comment]
Thank you
