### ISSUE TITLE
Add second column in each BAP Participate page

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#54]
![cap65](https://cloud.githubusercontent.com/assets/20802030/18018808/ddb67dd0-6b8d-11e6-9791-693fbe568849.PNG)

1.	On each of the /africa-bap.html, /asia-me-bap.html, /me-bap.html, /sa-bap.html, /ca-car-bap.html add a second column and add the embedded code that is on the /request_pricing.html below.
a.	<iframe width="1000" height="700" frameborder="0" src="https://app.smartsheet.com/b/form?EQBCT=cc948de8b00a4261b942ad59f5d8e54e"></iframe>
2.	Add a text area under each headline above the web form so I can add text that eill explain each of the two different pricing requests.
a.	The goal is to use one pricing request page but separate the standard pricing for 1 or more specific locations that are urgent. The BAP is when we collaborate with many NGOs to group a larger order together with the ISP.

**Comment by ariperez** [comment]
I added the second webfrom to each page.  

I cannot modify the space under the title since it is part of the form and not created by our code.

**Comment by ariperez** [comment]
You can probably place the desired text above each form within the following HTML markup:
```
<p class="flow-text">
Desired Text
</p>
```

**Comment by dataguy23us** [comment]
Ari,

<p class="flow-text">
Desired Text
</p>

Can you confirm where in the code I should add the suggested code (above in the code below) in each column?

<div class="container">
	<div class="row">
	</div>
	<div class="row">
    <div class="col s6">
			<iframe width="100%" height="2000" frameborder="0" src="https://app.smartsheet.com/b/form?EQBCT=e4d5cf533ad44532b6f0c09b223a0fad"></iframe>
    </div>
    <div class="col s6">
    	<iframe width="100%" height="1600" frameborder="0" src="https://app.smartsheet.com/b/form?EQBCT=cc948de8b00a4261b942ad59f5d8e54e"></iframe>
    </div>
</div>

**Comment by dataguy23us** [comment]
Thank you
