### ISSUE TITLE
Add Our News or Our Blog to upper nav bar

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#59]
![cap70](https://cloud.githubusercontent.com/assets/20802030/18019176/c92e2b4a-6b8f-11e6-85fe-8d014daef21d.PNG)

Create a new page for the Our News where we are able to add updates

**Comment by ariperez** [comment]
just as a heads up, the Jekyll engine we used to build this site is perfect as a blogging engine.  You can probably find several people able to turn this our news sections into a blog type news feed.
https://jekyllrb.com/

**Comment by ariperez** [comment]
I added an Our News section with some base HTML

**Comment by dataguy23us** [comment]
Thank you
