### ISSUE TITLE
Staff Member Change

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#6]
- [x] Adjust the images to all be the same size and is responsive? 

- [x] Change Our Charity Organizers to Our Staff
![cap 4](https://cloud.githubusercontent.com/assets/20802030/17344506/36051b5c-58b7-11e6-883f-82d0cfa15201.PNG)

**Comment by ariperez** [comment]
@dataguy23us : Let me know if the most recent updates resolve this issue.

**Comment by dataguy23us** [comment]
Resolved and I will close the task
